services:
  - type: web
    name: shadowban-checker
    env: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: RENDER
        value: true
